[package]
name = "cluster"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gate"
path = "src/gate.rs"

[[bin]]
name = "cluster"
path = "src/cluster.rs"

[[bin]]
name = "game"
path = "src/game.rs"

[dependencies]
